| Unit    | Change                                                                                                                                                                                                                    |
|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 0.2     | Toothbrush activity option added to Do Now  World Cafe protocol added for Lab                                                                                                                                             |
| 0.4     | Student Experiences Survey added and updated lab files uploaded                                                                                                                                                           |
| 1.1     | Diverse Grouping guidance added for lab Helping Trios handout added as Accommodation/Differentiation                                                                                                                      |
| 1.2     | Options added to Do Now and Activity Cold Calling Alternative protocol added                                                                                                                                              |
| 1.3     | Geometry Cheat Sheet handout added                                                                                                                                                                                        |
| 2.1     | Do Now option added Geometry Cheat Sheet handout added                                                                                                                                                                    |
| 2.2     | Lab challenge activity edited to personalize  Diverse Grouping reminder Cold Calling Alternative added in debrief                                                                                                         |
| 2.3     | An intro to conditionals video by Flocabulary added                                                                                                                                                                       |
| 2.4     | Variable Boxes Unplugged Activity added to Do Now as a intro to Variables                                                                                                                                                 |
| 2.5     | Boolean Expression Unplugged Activity added as intro to Boolean Expressions Reminder about diverse grouping Geometry Cheat Sheet handout added                                                                            |
| 3.1     | Lab edited to include options for personalization                                                                                                                                                                         |
| 3.2     | Do Now option added Reminder about diverse pairing                                                                                                                                                                        |
| 3.3     | Lab challenge edited to include personalization of No. 4 Edited lab files uploaded                                                                                                                                        |
| 4.2     | Do Now option added Lists Structure Handout Grammar Cheat Sheet handout accommodation added                                                                                                                               |
| 4.3     | Lab language change & uploaded new edited files  Diverse Grouping reminder                                                                                                                                                |
| 4.6     | Hangman project changed to Word Guessing game with edited handouts uploaded Snowman Snap! project replaces hangman example                                                                                                |
| 5.1     | Diverse grouping reminder                                                                                                                                                                                                 |
| 5.2     | New Space Invaders links added includes Vimeo link Lab now focusing on bouncing sprites instead of balls & updated files uploaded                                                                                         |
| 5.3     | Lab now focusing on bouncing sprites instead of balls & updated files uploaded  Helping Trios handout added                                                                                                               |
| 6.1     | TEALS final project examples added TEALS design steps handout added                                                                                                                                                       |
| 6.2     | Peer Feedback Handout added Inspirational software design video from Code.org added Diverse grouping reminder                                                                                                             |
| 6.3     | Links to Final Project Development Plan & Organizer added                                                                                                                                                                 |
| 6.4     | Links to Final Project Development Plan & Organizer added                                                                                                                                                                 |
| 6.5     | Wise Feedback protocol added Meerkating guidance added Links to Final Project Development Plan & Organizer                                                                                                                |
|         |                                                                                                                                                                                                                           |
| Overall | CRTchanges aim to provide for student choice, voice and agency in the curriculum. They include options and resources to address different learning styles and to personalize to the cultural specifics of your classroom. |
| Overall | "Unit Tips" documents have been added for each unit with helpful Snap! teaching tips relevant to the unit. It also includes definition of terms introduced in the unit that can be used on a classroom Word Wall.         |
